apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  labels:
    app: todolist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
        - name: todolist
          image: my-todolist:0.0.1
          ports:
            - containerPort: 8080
